version: '3.9'

services:
  client:
    build:
      context: ./client
    image: client_dev
    container_name: client_dev
    command: [yarn, dev]
    volumes:
      - ./client:/client
      - client_node_modules:/client/node_modules
      - client_dotnuxt:/client/.nuxt
    ports:
      - '8000:3000'
volumes:
  client_node_modules:
  client_dotnuxt:
